# Generated by Django 2.0 on 2019-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='author/avatar.jpg', upload_to='author/', verbose_name='头像'),
        ),
    ]
