# Generated by Django 2.0 on 2019-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='作者姓名'),
        ),
    ]
