# Generated by Django 2.0 on 2019-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '超时关闭'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_FINISHED', '交易结束')], default='WAIT_BUYER_PAY', max_length=50, verbose_name='订单状态'),
        ),
    ]
