# Generated by Django 2.0 on 2019-03-02 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('book', '0001_initial'),
        ('author', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='历史所属人.'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='评论书本'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='收藏书'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏人'),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='mark_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='标记书籍'),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='mark_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Chapter', verbose_name='书签章节'),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='mark_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='书签用户'),
        ),
        migrations.AddField(
            model_name='attention',
            name='attention_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author', verbose_name='关注作者'),
        ),
        migrations.AddField(
            model_name='attention',
            name='attention_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关注人'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkmodel',
            unique_together={('mark_user', 'mark_book')},
        ),
    ]
