# Generated by Django 2.0 on 2019-03-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20190310_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0, max_length=20, verbose_name='费用'),
            preserve_default=False,
        ),
    ]
