# Generated by Django 2.0 on 2019-03-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_order_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(verbose_name='费用'),
        ),
    ]
