# Generated by Django 2.0 on 2019-03-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20190310_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='支付编号'),
        ),
    ]
