# Generated by Django 2.0 on 2019-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_order_trade_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], verbose_name='订单状态'),
        ),
    ]
