# Generated by Django 2.0 on 2019-03-11 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190307_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0008_auto_20190311_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recommend_num', models.IntegerField(default=1, verbose_name='推荐数')),
                ('recommend_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='推荐书')),
                ('recommend_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='推荐人')),
            ],
            options={
                'verbose_name': '推荐信息',
                'verbose_name_plural': '推荐信息',
                'ordering': ('-recommend_num',),
            },
        ),
    ]
