# Generated by Django 2.0 on 2019-05-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
