# Generated by Django 2.0 on 2019-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='member_user',
        ),
        migrations.AlterField(
            model_name='member',
            name='ticket_num',
            field=models.IntegerField(default=0, verbose_name='推荐票数'),
        ),
    ]
