# Generated by Django 2.0 on 2019-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='book',
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(default='https://www.baidu.com/', verbose_name='轮播图连接'),
        ),
    ]
