# Generated by Django 2.0 on 2019-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190305_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('wx', '武侠小说'), ('xh', '玄幻小说'), ('ds', '都市言情'), ('kb', '恐怖灵异'), ('xd', '现代文学'), ('zt', '侦探推理'), ('kh', '科幻小说'), ('cy', '穿越架空'), ('gd', '古典名著'), ('ls', '历史军事'), ('wy', '网游小说')], max_length=20, verbose_name='小说分类'),
        ),
    ]
