# Generated by Django 2.0 on 2019-03-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190305_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已完结'), (1, '连载中')], default=1, verbose_name='状态'),
        ),
    ]
