# Generated by Django 2.0 on 2019-03-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
        migrations.AddField(
            model_name='banner',
            name='book',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='轮播图关联书'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='sort_number',
            field=models.IntegerField(default=0, max_length=20, verbose_name='章节序号'),
        ),
    ]
