# Generated by Django 2.0 on 2019-03-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190307_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='book',
            field=models.OneToOneField(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='轮播图关联书'),
        ),
    ]
