# Generated by Django 2.0 on 2019-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190307_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(max_length=200, upload_to='book/', verbose_name='小说封面'),
        ),
    ]
