# Generated by Django 2.0 on 2019-03-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190312_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('sort_number',), 'verbose_name': '章节信息', 'verbose_name_plural': '章节信息'},
        ),
    ]
