# Generated by Django 2.0 on 2019-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190314_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='小说名称'),
        ),
    ]
